os:
  - linux
  - osx

language: cpp

env:
  global:
    - secure: "AXHFIafTmbGDsHD3mUVj5a4I397DQjti/WoqAJGUp2PglxTcc04BwxZ9Z+xLuf5N2Hs5r9ojAJLT8OGxJCLBDXzneQTNSqXbFuYSLbqrEAiIRlA9eRIotWCg+wYcO+5e8MKX+cHVKwiIWasUB21AtCdq6msh6Y3pUshZp212VPg=" 

before_install:
 - sh .travis-deps.sh

script:
 - sh .travis-build.sh

after_success:
 - sh .travis-upload.sh
