# it seems that Qt is only installed by default on unstable os at the moment
os: unstable

# shallow clone
clone_depth: 1

environment:
  QTDIR: C:\Qt\5.4\msvc2013_64_opengl
  MEGA_EMAIL:
    secure: rEo9CGAYX87GKTqZCZ9vLCNCNqxO5JLgbERaHF3YJWg=
  MEGA_PASSWORD:
    secure: zE1zmgjS/6GfN/19ROl/O0fVR58svORQ5gdtsxI7J8k=

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12 Win64" ..
  - cd ..

after_build:
  # upload the build to Mega
  - cinst wget -x86
  - wget -q http://megatools.megous.com/builds/megatools-1.9.94-win64.zip
    # extract megatools silently. See http://stackoverflow.com/a/11629736/1748450
  - 7z x megatools-1.9.94-win64.zip | FIND /V "ing  "
    # copy the qt dlls
  - copy C:\Qt\5.4\msvc2013_64_opengl\bin\icudt53.dll build\bin\release
  - copy C:\Qt\5.4\msvc2013_64_opengl\bin\icuin53.dll build\bin\release
  - copy C:\Qt\5.4\msvc2013_64_opengl\bin\icuuc53.dll build\bin\release
  - copy C:\Qt\5.4\msvc2013_64_opengl\bin\Qt5Core.dll build\bin\release
  - copy C:\Qt\5.4\msvc2013_64_opengl\bin\Qt5Gui.dll  build\bin\release
  - copy C:\Qt\5.4\msvc2013_64_opengl\bin\Qt5OpenGL.dll build\bin\release
  - copy C:\Qt\5.4\msvc2013_64_opengl\bin\Qt5Widgets.dll  build\bin\release
  - mkdir build\bin\release\platforms\
  - copy C:\Qt\5.4\msvc2013_64_opengl\plugins\platforms\qwindows.dll build\bin\release\platforms
    # zip up the build folder -> build.7z
  - 7z a build .\build\bin\release\*
    # rename, upload to Mega
  - npm install sanitize-filename
  - cd megatools-1.9.94-win64
  - node ..\upload_to_mega.js
